[buildPlans.iosevka]
family = "Iosevka"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka.variants]
  inherits = "ss09"

    [buildPlans.iosevka.variants.design]
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    f = "serifless"
    i = "serifed"
    l = "tailed-serifed"
    t = "bent-hook"
    x = "straight-serifless"
    z = "straight-serifless"
    lower-alpha = "crossing"
    zero = "slashed"
    one = "base"
    two = "curly-neck"
    three = "flat-top"
    four = "closed-non-crossing"
    five = "oblique-upper-left-bar"
    six = "closed-contour"
    seven = "bend-serifless-crossbar"
    eight = "crossing-asymmetric"
    nine = "closed-contour"
    tilde = "low"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    ampersand = "upper-open"
    at = "compact"
    dollar = "open"
    percent = "rings-continuous-slash-also-connected"
    ascii-single-quote = "straight"
    question = "corner"
    pilcrow = "low"
    cent = "open"
    lig-ltgteq = "flat"
    lig-neq = "slightly-slanted-dotted"
    lig-equal-chain = "with-notch"
    lig-hyphen-chain = "with-notch"
    lig-double-arrow-bar = "with-notch"
    lig-single-arrow-bar = "with-notch"

  [buildPlans.iosevka.ligations]
  inherits = "clike"

[buildPlans.iosevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka.weights.extrabold]
shape = 800
menu = 800
css = 800

[buildPlans.iosevka.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
