[skills.commit-please]
source_url = "https://github.com/nomyfan/dotfiles/tree/skills/skills/commit-please"
slug = "nomyfan/dotfiles"
path = "skills/commit-please"
sha = "87e268ac11a6fca8f209453d289cb28605792f7c"
checksum = "sha256:2c5436cfcf54a28a1308d3ac0609269671394bdf31d2dca72595ea9dd044c232"

[skills.skill-creator]
source_url = "https://github.com/anthropics/skills/tree/main/skills/skill-creator"
slug = "anthropics/skills"
path = "skills/skill-creator"
sha = "b9e19e6f44773509fbdd7001d77ff41a49a486c1"
checksum = "sha256:b2bfe91d69ca99994c0566baede889e7d2b9bb8791c6b6106c5d387392f717f6"
