[skills.commit-please]
source_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/commit-please"
collection_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills"
slug = "nomyfan/dotfiles"
path = "skills/commit-please"
sha = "6d33bc618fb19fdc3f6221725cb6f7ff27071160"
checksum = "sha256:f2bcb297a8601d929af58aba5088d34d1092da8da54c93f0af32134207edd19a"

[skills.engineer-design]
source_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills/engineer-design"
collection_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills"
slug = "nomyfan/dotfiles"
path = "skills/engineer-skills/engineer-design"
sha = "fcf86cf917a30c705192d54acc1632e29668bfa9"
checksum = "sha256:d1782078bf6a3b7d9b119903d1eee229ade157cac5f30e3a4c2e4b12627bdde0"

[skills.engineer-implement]
source_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills/engineer-implement"
collection_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills"
slug = "nomyfan/dotfiles"
path = "skills/engineer-skills/engineer-implement"
sha = "e544e43c4ed0d2a375efe372bcd7a23b89ef7620"
checksum = "sha256:8c7d8a50cad666a2a1d98fb3af0ae8ab8c72d6d4c58c2a7c57520775dffe1f09"

[skills.engineer-requirement]
source_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills/engineer-requirement"
collection_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills"
slug = "nomyfan/dotfiles"
path = "skills/engineer-skills/engineer-requirement"
sha = "fcf86cf917a30c705192d54acc1632e29668bfa9"
checksum = "sha256:91a600f256be3c6c532d41b8f3aac6c901bbadb98c067539ebdd3725f69ea5bf"

[skills.engineer-review]
source_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills/engineer-review"
collection_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills"
slug = "nomyfan/dotfiles"
path = "skills/engineer-skills/engineer-review"
sha = "a0122add607c009fe0a90d895b2db54b67bd76c6"
checksum = "sha256:6aa53e7c52c023e785bd7d0d983460af53d9aedaa980bd56978382a6f4f591bc"

[skills.handoff]
source_url = "https://github.com/mattpocock/skills/tree/main/skills/productivity/handoff"
slug = "mattpocock/skills"
path = "skills/productivity/handoff"
sha = "386d4ff719a7c420ad1454232d0436b01f1b8c17"
checksum = "sha256:87e353708ab36062eac54ddb593a97ca553c0cb4bfa1ed1fdaf68520700723f1"

[skills.skill-creator]
source_url = "https://github.com/anthropics/skills/tree/main/skills/skill-creator"
slug = "anthropics/skills"
path = "skills/skill-creator"
sha = "b9e19e6f44773509fbdd7001d77ff41a49a486c1"
checksum = "sha256:b2bfe91d69ca99994c0566baede889e7d2b9bb8791c6b6106c5d387392f717f6"
