[skills.commit-please]
source_url = "https://github.com/nomyfan/dotfiles/tree/main/skills/commit-please"
slug = "nomyfan/dotfiles"
path = "skills/commit-please"
sha = "197c57ac24d4fa48a500d9c12aef9cfdf80d9853"
checksum = "sha256:5e33b1a22cf989e126cdfc043cc9e3fa1f84729536d826ea4451eedaa876ae20"

[skills.engineer-design]
source_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills/engineer-design"
collection_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills"
slug = "nomyfan/dotfiles"
path = "skills/engineer-skills/engineer-design"
sha = "6909b129af609f12595891522f4ff3aa2b90ffbb"
checksum = "sha256:eca3427394f869d061cb70aaebc1e046111e363d328acff2124b72f513691c84"

[skills.engineer-implement]
source_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills/engineer-implement"
collection_url = "https://github.com/nomyfan/dotfiles/tree/engineer-skills/skills/engineer-skills"
slug = "nomyfan/dotfiles"
path = "skills/engineer-skills/engineer-implement"
sha = "6909b129af609f12595891522f4ff3aa2b90ffbb"
checksum = "sha256:5528c9495842053b130798e112e883b7c74a58d0d0226bede17d22ea87ad510c"

[skills.handoff]
source_url = "https://github.com/mattpocock/skills/tree/main/skills/productivity/handoff"
slug = "mattpocock/skills"
path = "skills/productivity/handoff"
sha = "386d4ff719a7c420ad1454232d0436b01f1b8c17"
checksum = "sha256:87e353708ab36062eac54ddb593a97ca553c0cb4bfa1ed1fdaf68520700723f1"

[skills.skill-creator]
source_url = "https://github.com/anthropics/skills/tree/main/skills/skill-creator"
slug = "anthropics/skills"
path = "skills/skill-creator"
sha = "b9e19e6f44773509fbdd7001d77ff41a49a486c1"
checksum = "sha256:b2bfe91d69ca99994c0566baede889e7d2b9bb8791c6b6106c5d387392f717f6"
